import "package:flutter/material.dart";
import "package:google_fonts/google_fonts.dart";

ThemeData theme(ColorScheme colorScheme) => ThemeData(
      useMaterial3: true,
      colorScheme: colorScheme,
      brightness: colorScheme.brightness,
      scaffoldBackgroundColor: colorScheme.background,
      canvasColor: colorScheme.surface,
      textTheme: GoogleFonts.openSansTextTheme(ThemeData(brightness: colorScheme.brightness).textTheme).apply(
        bodyColor: colorScheme.onSurface,
        displayColor: colorScheme.onSurface,
      ),
    );

const ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF056FA0),
  surfaceTint: Color(0xFF006492),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF00496C),
  onPrimaryContainer: Color(0xFFFFFFFF),
  secondary: Color(0xFF14565D),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFF003349),
  onSecondaryContainer: Color(0xFFE5F4FF),
  tertiary: Color(0xFFE1EEED),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFF546160),
  onTertiaryContainer: Color(0xFF455151),
  error: Color(0xFF972522),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFE96158),
  onErrorContainer: Color(0xFFFFFFFF),
  background: Color(0xFFF7F9FE),
  onBackground: Color(0xFF002F44),
  surface: Color(0xFFF7F9FE),
  onSurface: Color(0xFF181C1F),
  surfaceVariant: Color(0xFFF7FCFF),
  onSurfaceVariant: Color(0xFFFFFFFF),
  outline: Color(0xFF707880),
  outlineVariant: Color(0xFFBFC7D0),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  inverseSurface: Color(0xFF2D3134),
  inversePrimary: Color(0xFF8BCEFF),
);

const ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF8BCEFF),
  surfaceTint: Color(0xFF8BCEFF),
  onPrimary: Color(0xFF00344E),
  primaryContainer: Color(0xFF006492),
  onPrimaryContainer: Color(0xFFFFFFFF),
  secondary: Color(0xFFA2CCE8),
  onSecondary: Color(0xFF00344A),
  secondaryContainer: Color(0xFF0B3D53),
  onSecondaryContainer: Color(0xFFA5CFEB),
  tertiary: Color(0xFFFFFFFF),
  onTertiary: Color(0xFF273332),
  tertiaryContainer: Color(0xFFCAD7D6),
  onTertiaryContainer: Color(0xFF364241),
  error: Color(0xFFFFB4AC),
  onError: Color(0xFF690007),
  errorContainer: Color(0xFFC94942),
  onErrorContainer: Color(0xFFFFFFFF),
  background: Color(0xFF101417),
  onBackground: Color(0xFFE0E3E7),
  surface: Color(0xFF101417),
  onSurface: Color(0xFFE0E3E7),
  surfaceVariant: Color(0xFF40484F),
  onSurfaceVariant: Color(0xFFBFC7D0),
  outline: Color(0xFF8A929A),
  outlineVariant: Color(0xFF40484F),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  inverseSurface: Color(0xFFE0E3E7),
  inversePrimary: Color(0xFF006492),
);
